### PR TITLE
Fixing Example.densify

### LINKED ISSUE #299: Including all the features in a tf-idf transformation of a Tribuo's example
Hello,

I am facing a problem while using Tribuo for a tf-idf transformation use case.

**My use case**

I would like to use Tribuo to create an tf-idf transformer that transforms a phrase into a vector. 

**My problem**

I would like every sentence to be projected into the space represented by the whole set of features (a vector containing a value for each word of my vocabulary for example). For example, if I train my transformer with the sentences "Hello I am John" and "Hello I am William", my set of features (my vocabulary) is : "HELLO", "I", "AM", "JOHN", "WILLIAM". When I transform a dataset containing these two sentences, it works (both sentences yield vectors in the space represented by the whole set of features).

But when I transform an example (even if I densify the example after the transformation), it does not include the features that are not present in the example itself in its representation. For instance, if I transform the example created from the sentence “Hello I am Charles”, the result is a vector in the space composed of the features "HELLO", "I", "AM”, “Charles” but "JOHN" and "WILLIAM” are missing. When I call the isDense method on this densified example, it returns false (and an investigation made me see that this comes from the fact that my example size is smaller than the features size despite the densification that I apply).

I added a code sample below to illustrate this problem and all the facts that I mention above. Please, does anyone see what I am doing wrong there?

Thank you in advance.

Victor

**Code sample**

```
import org.tribuo.Example;
import org.tribuo.MutableDataset;
import org.tribuo.classification.Label;
import org.tribuo.classification.LabelFactory;
import org.tribuo.data.columnar.FieldProcessor;
import org.tribuo.data.columnar.RowProcessor;
import org.tribuo.data.columnar.processors.field.TextFieldProcessor;
import org.tribuo.data.columnar.processors.response.FieldResponseProcessor;
import org.tribuo.data.text.impl.TokenPipeline;
import org.tribuo.datasource.ListDataSource;
import org.tribuo.transform.TransformationMap;
import org.tribuo.transform.TransformerMap;
import org.tribuo.transform.transformations.IDFTransformation;
import org.tribuo.util.tokens.impl.WhitespaceTokenizer;

import java.util.*;
import java.util.stream.Collectors;

public class TribuoTest {
    private static final String ATTRIBUTE_NAME = "PHRASE";

    public static void main(String[] args) {
        // create a row processor to create tribuo examples
        RowProcessor<Label> rowProcessor = createRowProcessor();

        // create data
        List<String> data = Arrays.asList(
                "Hello I am John",
                "Hello I am William"
        );
        List<Example<Label>> dataExamples = createExampleList(rowProcessor, data);
        MutableDataset<Label> dataset = createDataset(dataExamples);

        // create an IDF transformer
        TransformerMap transformer = createTransformer(dataset);

        // dataset tranformation
        MutableDataset<Label> tranformedDataset = transformer.transformDataset(dataset);
        System.out.println(tranformedDataset.getData());
        //[ArrayExample(numFeatures=4,output=HELLO I AM JOHN,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=John, 0.6931471805599453), (PHRASE@1-N=am, 0.0), ]), ArrayExample(numFeatures=4,output=HELLO I AM WILLIAM,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=William, 0.6931471805599453), (PHRASE@1-N=am, 0.0), ])]
        tranformedDataset.densify();
        System.out.println(tranformedDataset.getData());
        //[ArrayExample(numFeatures=5,output=HELLO I AM JOHN,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=John, 0.6931471805599453), (PHRASE@1-N=William, 0.0), (PHRASE@1-N=am, 0.0), ]), ArrayExample(numFeatures=5,output=HELLO I AM WILLIAM,weight=1.0,features=[(PHRASE@1-N=Hello, 0.0)(PHRASE@1-N=I, 0.0), (PHRASE@1-N=John, 0.0), (PHRASE@1-N=William, 0.6931471805599453), (PHRASE@1-N=am, 0.0), ])]
        System.out.println(tranformedDataset.getFeatureMap().keySet());
        //[PHRASE@1-N=John, PHRASE@1-N=am, PHRASE@1-N=Hello, PHRASE@1-N=I, PHRASE@1-N=William]

        // tribuo example tranformation
        String phrase = "Hello I am Charles";
        Example<Label> example = createExample(rowProcessor, phrase);
        Example<Label> transformedExample = transformer.transformExample(example);
        System.out.println(transformedExample);
        //ArrayExample(numFeatures=4,output=HELLO I AM CHARLES,weight=1.0,features=[(PHRASE@1-N=Charles, 1.0)(PHRASE@1-N=Hello, 0.0), (PHRASE@1-N=I, 0.0), (PHRASE@1-N=am, 0.0), ])
        transformedExample.densify(dataset.getFeatureMap());
        System.out.println(transformedExample);
        //ArrayExample(numFeatures=4,output=HELLO I AM CHARLES,weight=1.0,features=[(PHRASE@1-N=Charles, 1.0)(PHRASE@1-N=Hello, 0.0), (PHRASE@1-N=I, 0.0), (PHRASE@1-N=am, 0.0), ])
        System.out.println(transformedExample.isDense(dataset.getFeatureMap()));
        //false
    }

    private static RowProcessor<Label> createRowProcessor() {
        Map<String, FieldProcessor> fieldProcessors = Collections.singletonMap(
                ATTRIBUTE_NAME,
                new TextFieldProcessor(
                        ATTRIBUTE_NAME,
                        new TokenPipeline(new WhitespaceTokenizer(), 1, false)
                )
        );
        return new RowProcessor<>(
                new FieldResponseProcessor<>(
                        ATTRIBUTE_NAME,
                        "",
                        new LabelFactory()
                ),
                fieldProcessors
        );
    }

    private static MutableDataset<Label> createDataset(List<Example<Label>> exampleList) {
        return new MutableDataset<>(
                new ListDataSource<>(exampleList, new LabelFactory(), null)
        );
    }

    private static List<Example<Label>> createExampleList(RowProcessor<Label> rowProcessor, List<String> data) {
        return data.stream().map(d -> createExample(rowProcessor, d)).collect(Collectors.toList());
    }

    private static Example<Label> createExample(RowProcessor<Label> rowProcessor, String data) {
        Optional<Example<Label>> exampleOptional = rowProcessor.generateExample(
                Collections.singletonMap(
                        ATTRIBUTE_NAME,
                        data
                ),
                false);
        if (exampleOptional.isEmpty()) {
            throw new RuntimeException("Tribuo's example generation did not succeed");
        }
        return exampleOptional.get();
    }

    private static TransformerMap createTransformer(MutableDataset<Label> dataset) {
        TransformationMap transformationMap = new TransformationMap(Collections.singletonList(new IDFTransformation()));
        return dataset.createTransformers(transformationMap, true);
    }
}
```

### PR DESCRIPTION
**Pull request by Craigacp**
### Description
`Example.densify(List<String>)` behaved incorrectly if the list did not contain the feature names already present in the example. This PR fixes it so densify always adds zero valued features for any feature names not present in the example.

### Motivation
Fixes #299.

### CODE REVIEW

File: Core/src/main/java/org/tribuo/impl/IndexedArrayExample.java [hunk 1]
```diff
@@ -364,6 +364,11 @@ public IndexedArrayExample<T> copy() {
         return new IndexedArrayExample<>(this);
     }
 
+    /**
+     * Unlike {@link ArrayExample#densify(List)} this method will throw {@link IllegalArgumentException}
+     * if one of the feature names is not present in this example's {@link ImmutableFeatureMap}.
+     * @param featureList A *sorted* list of feature names.
```
Comment (JackSullivan) [inline Core/src/main/java/org/tribuo/impl/IndexedArrayExample.java:370]: the requirement that the input list be sorted should be more prominent in the docs

File: Core/src/main/java/org/tribuo/Example.java [hunk 2]
```diff
@@ -307,6 +307,8 @@ public void transform(TransformerMap transformerMap) {
 
     /**
      * Converts all implicit zeros into explicit zeros based on the supplied feature map.
```
Comment (JackSullivan) [inline Core/src/main/java/org/tribuo/Example.java:309]: This docstring should refer users to implementation specific docstrings that may impose restrictions (ie. must be sorted) on its input.

File: Core/src/main/java/org/tribuo/impl/ArrayExample.java [hunk 3]
```diff
@@ -530,32 +530,42 @@ public boolean isDense(FeatureMap fMap) {
 
     @Override
     public void densify(List<String> featureList) {
```
Comment (JackSullivan) [inline Core/src/main/java/org/tribuo/impl/ArrayExample.java:532]: This should document that it expects a sorted list

**Review by JackSullivan — CHANGES_REQUESTED** [review]
Needs clearer documentation around sorted list requirements

File: Core/src/main/java/org/tribuo/impl/ArrayExample.java (hunk 3 above)
Comment (Craigacp) [reply Core/src/main/java/org/tribuo/impl/ArrayExample.java:539]: Fixed.

File: Core/src/main/java/org/tribuo/Example.java (hunk 2 above)
Comment (Craigacp) [reply Core/src/main/java/org/tribuo/Example.java:309]: I added a note saying this method is optional and implementations may have additional restrictions.

File: Core/src/main/java/org/tribuo/impl/IndexedArrayExample.java (hunk 1 above)
Comment (Craigacp) [reply Core/src/main/java/org/tribuo/impl/IndexedArrayExample.java:373]: Fixed.

**Review by JackSullivan — APPROVED** [review]
Looks good to me
